config/routes.rb
Rails.application.routes.draw do

  # farmer
  devise_for :farmers, controllers: {
    sessions:      'farmers/sessions',
    registrations: 'farmers/registrations'
  }
  devise_scope :farmer do
    post 'farmers/guest_sign_in' => 'farmers/sessions#guest_sign_in'
  end

  namespace :farmers do
    resource :farmers, only: [:show, :edit, :update]
      get 'farmers/unsubscribe' => 'farmers#unsubscribe',  as: 'farmers_unsubscribe'
      patch 'farmers/withdraw'  => 'farmers#withdraw',     as: 'farmers_withdraw'
      get 'evaluations' => 'farmers#evaluations',  as: 'farmers_evaluations'
      get 'calender'    => 'farmers#calender',     as: 'farmers_calender'
    resources :recipes
    resources :events do
      resources :schedules, only: [:show, :edit, :update, :destroy]
      resources :chats, only: [:create]
    end
    resources :news, only: [:create, :destroy]
    resources :notices, only: [:index]
      delete 'notices/destroy_all' => 'notices#destroy_all'
  end

  # customer
  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    registrations: 'customers/registrations'
  }
  devise_scope :customer do
    post 'customers/guest_sign_in' => 'customers/sessions#guest_sign_in'
  end

  scope module: :customers do
    root 'homes#top'
    get 'about' => 'homes#about'
    get 'about_for_farmer' => 'homes#about_farmer'
    resources :events, only: [:index, :show] do
      resource :favorite_events, only: [:create, :destroy]
      resources :chats, only: [:create]
      resources :schedules, only: [:show] do
        get 'reservations/thanx'
        resources :reservations, only: [:new, :show, :create, :destroy]
        post 'reservations/confirm'
        post 'reservations/back'
      end
    end
    resources :farmers, only: [:index, :show] do
      resources :follows, only: [:create, :destroy]
      resources :evaluations, only: [:index, :create, :edit, :update, :destroy]
    end
    resources :notices, only: [:index]
      delete 'notices/destroy_all' => 'notices#destroy_all'
    resource :profiles, only: [:show, :edit, :update]
      get 'customer/followings' => 'profiles#followings', as: 'followings'
      get 'customer/favorites' => 'profiles#favorites', as: 'favorites'
      get 'customer/evaluations' => 'profiles#evaluations', as: 'evaluations'
      get 'customer/unsubscribe' => 'profiles#unsubscribe'
      patch 'customer/withdraw'  => 'profiles#withdraw'
    resources :recipes, only: [:index, :show] do
      resource :favorite_recipes, only: [:create, :destroy]
    end
    resources :reservations, only: [:index]
  end

  get 'search'=> 'searches#search', as: 'search'
  get 'sort'=> 'searches#sort', as: 'sort'

  # admin
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
  }

  namespace :admins do
    root 'farmers#index'
    resources :customers, only: [:index]
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable

  has_many :chats, dependent: :destroy
  has_many :evaluations, dependent: :destroy
  has_many :event_favorites, dependent: :destroy
  has_many :favorite_events, through: :event_favorites, source: :event
  has_many :follows, dependent: :destroy
  has_many :follow_farmers, through: :follows, source: :farmer
  has_many :recipe_favorites, dependent: :destroy
  has_many :favorite_recipes, through: :recipe_favorites, source: :recipe
  has_many :notices, dependent: :destroy
  has_many :reservations, dependent: :destroy

  validates :nickname, uniqueness: true, presence: true
  attachment :customer_image

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  def following?(farmer)
    follows.where(farmer_id: farmer.id).exists?
  end

  def reserved?(schedule)
    reservations.where(schedule_id: schedule.id).exists?
  end

  def self.guest_account
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.nickname = 'ゲスト'
      customer.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page]).reverse_order
  end
end

app/controllers/customers/chats_controller.rb
class Customers::ChatsController < ApplicationController
  before_action :authenticate_customer!
  skip_before_action :set_prefectures

  def create
    @chat = current_customer.chats.new(chat_params)
    @chat.event_id = params[:event_id]
    if @chat.save
      @chat.notice_created_by_customer(current_customer, params[:event_id])
    else
      render 'error'
    end
    @chats = Chat.where(event_id: params[:event_id])
  end

  private

  def chat_params
    params.require(:chat).permit(:chat)
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/evaluations_controller.rb
class Customers::EvaluationsController < ApplicationController
  before_action :authenticate_customer!, except: [:index]
  before_action :set_farmer, only: [:create, :edit]
  before_action :set_evaluation, only: [:edit, :update, :destroy]
  skip_before_action :set_prefectures

  def create
    @evaluation = current_customer.evaluations.new(evaluation_params)
    @evaluation.farmer_id = @farmer.id
    if @evaluation.save
      redirect_to farmer_path(@farmer), flash: { success: "レビューを投稿いたしました" }
    else
      redirect_to farmer_path(@farmer), flash: { danger: "星評価かコメントのいずれかを必ず入力してください。" }
    end
  end

  def index
    @evaluations = Evaluation.where(farmer_id: params[:farmer_id])
  end

  def edit
    unless current_customer.id == @evaluation.customer_id
      redirect_to profiles_path, flash: { danger: "他の方のレビューを編集することは出来ません" }
    end
  end

  def update
    if @evaluation.update(evaluation_params)
      redirect_to evaluations_path, flash: { success: "レビューを更新しました" }
    else
      render :edit
    end
  end

  def destroy
    @evaluation.destroy
    redirect_to evaluations_path, flash: { success: "レビューを削除しました" }
  end

  private

  def evaluation_params
    params.require(:evaluation).permit(:evaluation, :comment, :evaluation_image)
  end

  def set_farmer
    @farmer = Farmer.find(params[:farmer_id])
  end

  def set_evaluation
    @evaluation = Evaluation.find(params[:id])
  end
end

app/controllers/customers/events_controller.rb
class Customers::EventsController < ApplicationController
  def index
    @events = Event.where('end_date >= ?', Date.current).order(:start_date).page(params[:page])
  end

  def show
    @event = Event.find(params[:id])
    @schedules = @event.schedules.where(is_deleted: false, is_full: false)
    @schedule = @event.schedules.first
    @chat = Chat.new
    @chats = Chat.where(event_id: params[:id])
  end
end

app/controllers/customers/farmers_controller.rb
class Customers::FarmersController < ApplicationController
  def index
    @farmers = Farmer.where(is_deleted: false).page(params[:page]).reverse_order
  end

  def show
    @farmer = Farmer.find(params[:id])
    @events = Event.where(farmer_id: @farmer.id).where('end_date > ?', Date.current).order('created_at DESC').first(3)
    news_index = News.where(farmer_id: @farmer.id).order('created_at DESC')
    @news_last3 = news_index.first(3)
    @news_left = news_index.offset(3)
    @recipes = Recipe.where(farmer_id: @farmer.id).order('created_at DESC').first(3)

    @evaluation = Evaluation.new
    @evaluations = Evaluation.where(farmer_id: @farmer.id).order('created_at DESC').first(3)
    if @farmer.evaluations.blank?
      @average_rating = 0
    else
      @average_rating = @farmer.evaluations.average(:evaluation).round(2)
    end
  end
end

app/controllers/customers/favorite_events_controller.rb
class Customers::FavoriteEventsController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_event
  skip_before_action :set_prefectures

  def create
    favorite = @event.event_favorites.new(customer_id: current_customer.id)
    favorite.save
  end

  def destroy
    favorite = @event.event_favorites.find_by(customer_id: current_customer.id)
    favorite.destroy
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end
end

app/controllers/customers/favorite_recipes_controller.rb
class Customers::FavoriteRecipesController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_recipe
  skip_before_action :set_prefectures

  def create
    favorite = @recipe.recipe_favorites.new(customer_id: current_customer.id)
    favorite.save
  end

  def destroy
    favorite = @recipe.recipe_favorites.find_by(customer_id: current_customer.id)
    favorite.destroy
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:recipe_id])
  end
end

app/controllers/customers/follows_controller.rb
class Customers::FollowsController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_farmer
  skip_before_action :set_prefectures

  def create
    follow = @farmer.follows.new(customer_id: current_customer.id)
    follow.save
    @farmer.find_or_create_notice_of_follow(current_customer)
  end

  def destroy
    @farmer.follows.find_by(customer_id: current_customer.id).destroy
  end

  private

  def set_farmer
    @farmer = Farmer.find(params[:farmer_id])
  end
end

app/controllers/customers/homes_controller.rb
class Customers::HomesController < ApplicationController
  def top
    @farmers = Farmer.where(is_deleted: false).reverse_order.first(3)
    @recipes = Recipe.all.reverse_order.first(3)
    @events = Event.where("end_date >= ?", Date.current).reverse_order.first(3)
  end

  def about
  end
end

app/controllers/customers/notices_controller.rb
class Customers::NoticesController < ApplicationController
  skip_before_action :set_prefectures

  def index
    notices = current_customer.notices
    @notices = notices.where(action: ["チャット", "農業体験の内容更新", "農業体験のスケジュール更新", "お知らせ"]).order('created_at DESC').first(20)
    if notices.exists?
      unchecked_notices = notices.where(checked: false)
      unchecked_notices.update_all(checked: true)
    end
  end

  def destroy_all
    current_customer.notices.where(action: ["チャット", "農業体験の内容更新", "農業体験のスケジュール更新", "お知らせ"]).destroy_all
    redirect_to profiles_path, flash: { success: '通知をすべて削除しました' }
  end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/profiles_controller.rb
class Customers::ProfilesController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_customer
  skip_before_action :set_prefectures

  def show
  end

  def edit
    unless current_customer == @customer
      redirect_to profiles_path, flash: { danger: "他の方のプロフィールの変更は出来ません"}
    end
  end

  def update
    if @customer.update(customer_params)
      redirect_to profiles_path, flash: { success: "登録情報を更新しました" }
    else
      render :edit
    end
  end

  def unsubscribe
  end

  def withdraw
    @customer.update(is_deleted: true)
    redirect_to root_path, flash: { success: "ご利用いただき大変ありがとうございました！またのご利用を心よりお待ちしております。"}
  end

  def evaluations
    @evaluations = current_customer.evaluations
  end

  def favorites
    @favorite_recipes = current_customer.favorite_recipes
    @favorite_events = current_customer.favorite_events
  end

  def followings
    @followings = current_customer.follow_farmers.where(is_deleted: false).page(params[:page]).reverse_order
  end

  private

  def set_customer
    @customer = current_customer
  end

  def customer_params
    params.require(:customer).permit(:nickname, :customer_image)
  end
end

app/controllers/customers/recipes_controller.rb
class Customers::RecipesController < ApplicationController
  skip_before_action :set_prefectures

  def index
    @recipes = Recipe.page(params[:page]).reverse_order
  end

  def show
    @recipe = Recipe.find(params[:id])
    @tag_list = @recipe.tags.pluck(:tag)
  end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
        Customers::WelcomeMailer.complete_registration(resource).deliver_now
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
   def after_sign_up_path_for(resource)
    profiles_path
   end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #  super
  # end
end

app/controllers/customers/schedules_controller.rb
class Customers::SchedulesController < ApplicationController
  skip_before_action :set_prefectures

  def show
    @event = Event.find(params[:event_id])
    @schedule = @event.schedules.find(params[:id])
  end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

   def after_sign_in_path_for(resource)
    profiles_path
   end

   def after_sign_out_path_for(resource)
    root_path
   end

   def guest_sign_in
    customer = Customer.guest_account
    customer.update(is_deleted: false)
    sign_in customer
    redirect_to profiles_path, flash: { success: 'ゲスト住民としてログインしました' }
   end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/views/customers/homes/_area.html.erb
<div class="search-area-group mt-3">
  <div class="form-group">
    <h6>北海道・東北</h6>
    <% northern.each do |prefecture| %>
      <%= link_to prefecture, search_path(prefecture: prefecture) %>
    <% end %>
  </div>
  <div class="form-group">
    <h6>関東</h6>
    <% kanto.each do |prefecture| %>
      <%= link_to prefecture, search_path(prefecture: prefecture) %>
    <% end %>
  </div>
  <div class="form-group">
    <h6>中部</h6>
    <% middle.each do |prefecture| %>
      <%= link_to prefecture, search_path(prefecture: prefecture) %>
    <% end %>
  </div>
  <div class="form-group">
    <h6>関西</h6>
    <% kansai.each do |prefecture| %>
      <%= link_to prefecture, search_path(prefecture: prefecture) %>
    <% end %>
  </div>
  <div class="form-group">
    <h6>中国・四国</h6>
    <% western.each do |prefecture| %>
      <%= link_to prefecture, search_path(prefecture: prefecture) %>
    <% end %>
  </div>
  <div class="form-group">
    <h6>九州・沖縄</h6>
    <% southern.each do |prefecture| %>
      <%= link_to prefecture, search_path(prefecture: prefecture) %>
    <% end %>
  </div>
</div>

app/views/customers/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 mx-auto my-4">
      <section id="about-contents" class="text-center">
        <h4 class="mb-4">vegicircle（ベジサークル）について</h4>
        <p>vegecircleは、誰にも届くことなく消えていく食材を
          <br>その土地に住まわれる皆様へ繋ぐマッチングサイトです。</p>

        <p>母の実家へ遊びに行ったとき、規格に合わず、売れない野菜をトラクターで轢きながら
          <br>畑と混ぜていく景色を見たときの衝撃は今でも忘れられません。</p>

        <p>一時だけではなく、この先もずっとフードロスを減らす仕組みを作りたいと考えたとき、行きついた答えが、</p>
        <h5>「地産地消」そして「食育」でした。</h5><br>

        <p>ぜひ、このサイトを通じて身近な<strong>直売所</strong>に出向いていただき、おいしい食材を召し上がってください。
          <br>見慣れぬ食材で献立に迷われたら、<strong>レシピ</strong>もございます。
          <br>お子さんとの時間を増やしたい、お出かけしたいときには「<strong>農業体験</strong>」はいかがでしょうか。</p>

        <p>失われていく命を、その土地のみんなで美味しくいただき、
        <br>農家さん、住民の皆さま、地元の食材を丸く繋いでいく。</p>

        <p>そんな気持ちを込めて、「vegetable（野菜）」と「circle（円）」を掛け合わせ、「<strong>vegecircle</strong>」はできました。</p>
      </section>
    </div>
  </div>

  <div class="row">
    <div id="container" class="mx-auto mb-5">
      <div id="theTarget">
        <div class="image1"></div>
        <div class="image2"></div>
        <div class="image3"></div>
        <div class="image4"></div>
        <div class="image5"></div>
      </div>
    </div>
  </div>
</div>

app/views/customers/homes/about_farmer.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 mx-auto my-4">
      <section id="about-contents" class="text-center">
        <h4 class="mb-4">Vegicircle（ベジサークル）でできること</h4><br>
        <p>vegecircleは、誰にも届くことなく消えていく食材を
          <br>その土地に住まわれる皆様へ繋ぐマッチングサイトです。</p><br>

        <h5>直売所の場所を共有し、より多くの人に届けるお手伝いに活用ください。</h5><br>
        <p>野菜、お花など、何でも構いません。<br>
           あなたの直売所を、住民の皆さんに知っていただくきっかけとなれば幸いです。</p><br>

        <%= link_to "本サイトへのご登録はこちらから", new_farmer_registration_path, class: "btn btn-danger mb-5" %>

        <h5>◆ Vegecircleでレシピ投稿 ◆</h5><br>
        <p>住民の方にとっては、「これは初めて食べる！」という素材があることもあります。
        <br>ぜひ、皆様のご家庭のレシピを共有してください！</p>

        <div class="d-flex flex-row">
          <%= image_tag asset_path('about/f_image1.jpg'), class: "rounded-circle mr-3", width: '30%' %>
          <%= image_tag asset_path('about/f_image2.jpg'), class: "rounded-circle mr-3", width: '30%' %>
          <%= image_tag asset_path('about/f_image3.jpg'), class: "rounded-circle", width: '30%' %>
        </div>

        <h5 class="mt-5">◆ 農業体験の募集 ◆</h5><br>
        <p>農作物の収穫や植え付けなど、企画として住民の方を募集いただけないでしょうか。
        <br>最近は、野菜や果物が元々どのような姿なのか、苗はどんな形なのか知らないお子さんの方が多いと思います。</p>

        <p>農業体験を通じて地域の方々とのつながりを深めたり、<br>
        皆様の自信の商品をより多くの方々に知っていただくきかっけにしていただけたら嬉しいです。</p>
          <%= image_tag asset_path('about/f_image4.jpg'), class: "img-fluid" %>
        <%= link_to "本サイトへのご登録はこちらから", new_farmer_registration_path, class: "btn btn-danger mt-5" %>
        </div>
      </section>
    </div>
  </div>
</div>

app/views/customers/homes/top.html.erb
<section id="mv">
  <div class="container">
    <div class="row" id="mv-message">
      <div class="col-10 col-md-4 offset-1">
        <%= image_tag asset_path('top/main_logo.png'), class: "img-fluid" %>
      </div>
        <div class="m-auto text-center">
          <h2 class="my-5">べ ジ サ ー ク ル</h2>
          <p>誰にも届かないまま消えていく大切ないのちを</p>
          <p>生まれた土地で、おいしくいただく。</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="main-contents" class="mt-5">
  <div class="container">
    <div class="row">
      <div class="col-10 col-md-3 side-bar">
        <h5>エリアから農家を探す</h5>
        <%= render 'searches/farmer_area', regions: @regions %>
      </div>
      <div class="col-md-8 main-content d-none d-md-block ml-3">
        <div class="form-group mb-4">
          <div class="d-flex flex-row">
            <h5>新着農家</h5>
            <%= link_to ">> もっと見る", farmers_path, class: "ml-5 text-dark" %>
          </div>
          <%= render 'customers/farmers/index', farmers: @farmers %>
        </div>
        <div class="form-group mb-4">
          <div class="d-flex flex-row">
            <h5>新着レシピ</h5>
            <%= link_to ">> もっと見る", recipes_path, class: "ml-5 text-dark" %>
          </div>
          <%= render 'customers/recipes/index', recipes: @recipes %>
        </div>
        <div class="form-group mb-4">
          <div class="d-flex flex-row">
            <h5>新着農業体験</h5>
            <%= link_to ">> もっと見る", events_path, class: "ml-5 text-dark" %>
          </div>
          <%= render 'customers/events/index', events: @events %>
        </div>
      </div>
      <% unless customer_signed_in? || farmer_signed_in? %>
        <%= link_to customers_guest_sign_in_path, method: :post, class: "guest-login", id: "customer"  do %>ゲスト<br>ログイン<% end %>
        <%= link_to farmers_guest_sign_in_path, method: :post, class: "guest-login", id: "farmer" do %>ゲスト<br>ログイン<br>（農家）<% end %>
      <% end %>
    </div>
  </div>
</section>