config/routes.rb
Rails.application.routes.draw do

  # farmer
  devise_for :farmers, controllers: {
    sessions:      'farmers/sessions',
    registrations: 'farmers/registrations'
  }
  devise_scope :farmer do
    post 'farmers/guest_sign_in' => 'farmers/sessions#guest_sign_in'
  end

  namespace :farmers do
    resource :farmers, only: [:show, :edit, :update]
      get 'farmers/unsubscribe' => 'farmers#unsubscribe',  as: 'farmers_unsubscribe'
      patch 'farmers/withdraw'  => 'farmers#withdraw',     as: 'farmers_withdraw'
      get 'evaluations' => 'farmers#evaluations',  as: 'farmers_evaluations'
      get 'calender'    => 'farmers#calender',     as: 'farmers_calender'
    resources :recipes
    resources :events do
      resources :schedules, only: [:show, :edit, :update, :destroy]
      resources :chats, only: [:create]
    end
    resources :news, only: [:create, :destroy]
    resources :notices, only: [:index]
      delete 'notices/destroy_all' => 'notices#destroy_all'
  end

  # customer
  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    registrations: 'customers/registrations'
  }
  devise_scope :customer do
    post 'customers/guest_sign_in' => 'customers/sessions#guest_sign_in'
  end

  scope module: :customers do
    root 'homes#top'
    get 'about' => 'homes#about'
    get 'about_for_farmer' => 'homes#about_farmer'
    resources :events, only: [:index, :show] do
      resource :favorite_events, only: [:create, :destroy]
      resources :chats, only: [:create]
      resources :schedules, only: [:show] do
        get 'reservations/thanx'
        resources :reservations, only: [:new, :show, :create, :destroy]
        post 'reservations/confirm'
        post 'reservations/back'
      end
    end
    resources :farmers, only: [:index, :show] do
      resources :follows, only: [:create, :destroy]
      resources :evaluations, only: [:index, :create, :edit, :update, :destroy]
    end
    resources :notices, only: [:index]
      delete 'notices/destroy_all' => 'notices#destroy_all'
    resource :profiles, only: [:show, :edit, :update]
      get 'customer/followings' => 'profiles#followings', as: 'followings'
      get 'customer/favorites' => 'profiles#favorites', as: 'favorites'
      get 'customer/evaluations' => 'profiles#evaluations', as: 'evaluations'
      get 'customer/unsubscribe' => 'profiles#unsubscribe'
      patch 'customer/withdraw'  => 'profiles#withdraw'
    resources :recipes, only: [:index, :show] do
      resource :favorite_recipes, only: [:create, :destroy]
    end
    resources :reservations, only: [:index]
  end

  get 'search'=> 'searches#search', as: 'search'
  get 'sort'=> 'searches#sort', as: 'sort'

  # admin
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
  }

  namespace :admins do
    root 'farmers#index'
    resources :customers, only: [:index]
  end

end

app/controllers/admins/farmers_controller.rb
class Admins::FarmersController < ApplicationController
  def index
    @farmers = Farmer.page(params[:page]).reverse_order
  end
end

app/controllers/customers/farmers_controller.rb
class Customers::FarmersController < ApplicationController
  def index
    @farmers = Farmer.where(is_deleted: false).page(params[:page]).reverse_order
  end

  def show
    @farmer = Farmer.find(params[:id])
    @events = Event.where(farmer_id: @farmer.id).where('end_date > ?', Date.current).order('created_at DESC').first(3)
    news_index = News.where(farmer_id: @farmer.id).order('created_at DESC')
    @news_last3 = news_index.first(3)
    @news_left = news_index.offset(3)
    @recipes = Recipe.where(farmer_id: @farmer.id).order('created_at DESC').first(3)

    @evaluation = Evaluation.new
    @evaluations = Evaluation.where(farmer_id: @farmer.id).order('created_at DESC').first(3)
    if @farmer.evaluations.blank?
      @average_rating = 0
    else
      @average_rating = @farmer.evaluations.average(:evaluation).round(2)
    end
  end
end

app/controllers/customers/schedules_controller.rb
class Customers::SchedulesController < ApplicationController
  skip_before_action :set_prefectures

  def show
    @event = Event.find(params[:event_id])
    @schedule = @event.schedules.find(params[:id])
  end
end

app/controllers/farmers/chats_controller.rb
class Farmers::ChatsController < ApplicationController
  before_action :authenticate_farmer!
  skip_before_action :set_prefectures

  def create
    @chat = current_farmer.chats.new(chat_params)
    @chat.event_id = params[:event_id]
    if @chat.save
      @chat.notice_created_by(current_farmer)
    else
      render 'error'
    end
    @chats = Chat.where(event_id: params[:event_id])
  end

  private

  def chat_params
    params.require(:chat).permit(:chat)
  end
end

app/controllers/farmers/confirmations_controller.rb
# frozen_string_literal: true

class Farmers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/farmers/events_controller.rb
class Farmers::EventsController < ApplicationController
  before_action :authenticate_farmer!
  before_action :set_event, only: [:show, :edit, :update, :destroy, :withdraw]
  before_action :set_schedule, only: [:show, :edit, :update, :destroy, :withdraw]
  skip_before_action :set_prefectures

  def new
    @event = Event.new
  end

  def create
    @event = current_farmer.events.new(event_params)
    if @event.save
      @event.create_schedules(current_farmer)
      if @event.has_schedules?
        number_of_days = @event.end_date - @event.start_date
        if @event.schedules.size == number_of_days + 1
          redirect_to farmers_event_path(@event), flash: { success: '農業体験を作成しました' }
        else
          @event.date_update
          redirect_to farmers_event_path(@event), flash: { danger: '既に作成済みのイベントと日付が重なっていたもの以外作成しました' }
        end
      else
        @event.destroy
        flash.now[:danger] = '作成済みのイベントと日程が重なっており、作成できませんでした（イベントは1日ひとつまで）'
        render :new
      end
    else
      render :new
    end
  end

  def show
    @schedule = @schedules.first
    @chats = Chat.where(event_id: params[:id])
    if current_farmer.id == @event.farmer_id
      @chat = Chat.new
    end
  end

  def index
    @events = current_farmer.events.where("end_date >= ?", Date.current).order(:start_date).page(params[:page])
    @ended_events = current_farmer.events.where("end_date < ?", Date.current).order(:start_date).page(params[:page])
  end

  def edit
    if current_farmer.id != @event.farmer_id
      redirect_to farmers_event_path(@event), flash: { danger: '他の農家さんの農業体験なので編集できません' }
    elsif @event.start_date <= Date.current
      redirect_to farmers_event_path(@event), flash: { warning: 'イベント実施中/終了済みのため編集できません' }
    else
      @schedules = Schedule.where(event_id: @event.id).pluck(:date)
    end
  end

  def update
    if @event.update(event_params)
      redirect_to farmers_event_path(@event), flash: { success: '農業体験を更新しました' }
      @event.notice_create
    else
      @schedules = Schedule.where(event_id: @event.id).pluck(:date)
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to farmers_farmers_calender_path, flash: { success: '農業体験を削除しました'}
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def set_schedule
    @schedules = Schedule.where(event_id: @event.id)
  end

  def event_params
    params.require(:event).permit(:title, :plan_image, :body, :fee, :cancel_change, :start_date, :end_date, :location, :access, :parking, :etc, :is_deleted, :start_time, :end_time, :number_of_participants)
  end
end

app/controllers/farmers/farmers_controller.rb
class Farmers::FarmersController < ApplicationController
  before_action :authenticate_farmer!
  before_action :set_farmer, only: [:edit, :update, :withdraw]
  skip_before_action :set_prefectures

  def show
    @news = News.new
    @chat = Chat.new
    news_index = News.where(farmer_id: current_farmer.id).order('created_at DESC')
    @news_last3 = news_index.first(3)
    @news_left = news_index.offset(3)
    @recipes = Recipe.where(farmer_id: current_farmer.id).order('created_at DESC').first(3)
    @events = Event.where(["farmer_id = ? and end_date >= ?", current_farmer.id, Date.current]).order('start_date ASC').first(3)
    @evaluations = Evaluation.where(farmer_id: current_farmer.id).order('created_at DESC').first(3)

    if current_farmer.evaluations.exists?
      @average_rating = current_farmer.evaluations.average(:evaluation).round(2)
    else
      @average_rating = 0
    end
  end

  def edit
  end

  def update
    if @farmer.update(farmer_params)
      redirect_to farmers_farmers_path, flash: { success: "登録情報を更新しました" }
    else
      render :edit
    end
  end

  def unsubscribe
  end

  def withdraw
    @farmer.update(is_deleted: true)
    current_farmer.events.where("start_date > ?", Date.current).destroy_all
    redirect_to root_path, flash: { success: "ご利用いただき大変ありがとうございました！またのご利用を心よりお待ちしております" }
  end

  def evaluations
    @evaluations = current_farmer.evaluations
  end

  def calender
    @schedules = current_farmer.schedules.where(event_id: current_farmer.events.ids)
    @reservations = current_farmer.reservations
  end

  private

  def set_farmer
    @farmer = Farmer.find(current_farmer.id)
  end

  def farmer_params
    params.require(:farmer).permit(:name, :phone, :farm_address, :store_address, :introduction, :farmer_image, :image_1, :image_2, :image_3)
  end
end

app/controllers/farmers/news_controller.rb
class Farmers::NewsController < ApplicationController
  before_action :authenticate_farmer!
  skip_before_action :set_prefectures

  def create
    @news = current_farmer.news.new(news_params)
    if @news.save
      @news.notice_created_by(current_farmer)
      redirect_to farmers_farmers_path, flash: { success: "お知らせを投稿しました" }
    else
      @farmer = current_farmer
      news_index = News.where(farmer_id: @farmer.id).order('created_at DESC')
      @news_last3 = news_index.first(3)
      @news_left = news_index.offset(3)
      @recipes = Recipe.where(farmer_id: @farmer.id).order('created_at DESC').first(5)
      @events = Event.where(farmer_id: @farmer.id).order('created_at DESC').first(5)
      @evaluations = Evaluation.where(farmer_id: params[:id]).order('created_at DESC').first(3)
      render template: "farmers/farmers/show"
    end
  end

  def destroy
    news = News.find(params[:id])
    news.destroy
    news_index = News.where(farmer_id: current_farmer.id).order('created_at DESC')
    @news_last3 = news_index.first(3)
    @news_left = news_index.offset(3)
  end

  private

  def news_params
    params.require(:news).permit(:news, :news_image)
  end
end

app/controllers/farmers/notices_controller.rb
class Farmers::NoticesController < ApplicationController
  skip_before_action :set_prefectures

  def index
    notices = current_farmer.notices
    @notices = notices.where(action: ["フォロー", "チャット", "予約"]).order('created_at DESC').first(20)
    if notices.exists?
      unchecked_notices = notices.where(checked: false)
      unchecked_notices.update_all(checked: true)
    end
  end

  def destroy_all
    current_farmer.notices.where(action: ["フォロー", "チャット", "予約"]).destroy_all
    redirect_to farmers_farmers_path, flash: { success: '通知をすべて削除しました' }
  end
end

app/controllers/farmers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Farmers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/farmers/passwords_controller.rb
# frozen_string_literal: true

class Farmers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/farmers/recipes_controller.rb
class Farmers::RecipesController < ApplicationController
  before_action :authenticate_farmer!
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  skip_before_action :set_prefectures

  def index
    @recipes = current_farmer.recipes.page(params[:page]).reverse_order
  end

  def show
    @recipe = Recipe.find(params[:id])
    @tag_list = @recipe.tags.pluck(:tag)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_farmer.recipes.new(recipe_params)
    @tag_list = params[:recipe][:tag_list].split(',')
    if @recipe.save
      @recipe.save_tags(@tag_list)
      redirect_to farmers_recipe_path(@recipe), flash: {success: "レシピを作成しました"}
    else
      render :new
    end
  end

  def edit
    if current_farmer.id == @recipe.farmer_id
      @tag_list = @recipe.tags.pluck(:tag).join(",")
    else
      redirect_to farmers_recipe_path(@recipe), flash: {danger: "作成者のみ編集が可能です"}
    end
  end

  def update
    tag_list = params[:recipe][:tag_list].split(',')
    if @recipe.update_attributes(recipe_params)
      @recipe.save_tags(tag_list)
      redirect_to farmers_recipe_path(params[:id]), flash: {success: "レシピを更新しました"}
    else
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    redirect_to farmers_farmers_path, flash: {success: "レシピを削除しました"}
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:title, :recipe_image, :duration, :amount, :ingredient, :recipe, :tag_list)
  end
end

app/controllers/farmers/registrations_controller.rb
# frozen_string_literal: true

class Farmers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
   def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
        Farmers::WelcomeMailer.complete_registration(resource).deliver_now
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
   end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :farm_address, :store_address])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    farmers_farmers_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #  super
  # end
end

app/controllers/farmers/unlocks_controller.rb
# frozen_string_literal: true

class Farmers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/farmers_helper.rb
module Admins::FarmersHelper
end

app/helpers/customers/farmers_helper.rb
module Customers::FarmersHelper
end

app/views/farmers/schedules/_show.html.erb
<div class="row">
  <div class="col-12 col-md-10 mx-auto mb-2 event">
    <h5 class="mb-2">イベント概要</h5>
    <table class="table">
      <tbody>
        <tr>
          <th>イベント開催日時</th>
          <td class="d-flex align-items-center">
            <%= show_date(schedule.date) %>
            <div class="mx-3"><%= show_time(schedule.start_time) %> ～ <%= show_time(schedule.end_time) %></div>
            <% if current_farmer.id == event.farmer_id %>
              <% if schedule.date > Date.current %>
                <%= link_to "編集する", edit_farmers_event_schedule_path(event.id, schedule), class: "btn btn-success" %>
              <% end %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th>イベント参加費（税込）/人</th>
          <td><%= converting_to_jpy(event.fee) %></td>
        </tr>
        <tr>
          <th>予約可能人数（最大）</th>
          <td><%= schedule.people %>人</td>
        </tr>
        <tr>
          <th>キャンセルポリシー</th>
          <td><%= event.cancel_change %></td>
        </tr>
        <tr>
          <th>そのほか</th>
          <td><%= event.etc %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/farmers/schedules/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-11 col-md-8 mx-auto bg-gray p-5">
      <h4><%= @event.title %>の日程編集</h4>

      <%= render 'layouts/error_messages', validation: @schedule %><br>
      <%= form_with model: [:farmers, @event, @schedule], local: true do |f| %>

        <div class="col-10 mx-auto mb-3">
          <h5 class="mb-2">スケジュール</h5>
          <p><%= show_date(@schedule.date) %>　<%= show_time(@schedule.start_time) %> ～ <%= show_time(@schedule.end_time) %></p>
          <p class="ml-5">↓</p>
          <div class="form-row">
            <div class="form-group mr-3">
              <%= f.label :date, "日程" %><string class="required"> *</string><br />
              <%= f.date_field :date, class: "form-control form-control-sm" %>
            </div>
            <div class="form-group mr-3">
              <%= f.label :start_time, "開始時刻" %><string class="required"> *</string><br />
              <%= f.time_field :start_time, class: "form-control form-control-sm" %>
            </div>
            <div class="form-group">
              <%= f.label :end_time, "終了時刻" %><string class="required"> *</string><br />
              <%= f.time_field :end_time, class: "form-control form-control-sm" %>
            </div>
          </div>
        </div>

        <div class="col-10 mx-auto mb-3">
          <h5 class="mb-2">予約可能人数</h5>
          <p><%= @schedule.people %>人</p>
          <p class="ml-5">↓</p>
          <div class="form-row align-items-end">
            <div class="form-group">
              <%= f.label :people, "1日あたりの予約可能人数" %><string class="required"> *</string><br />
              <%= f.number_field :people, class: "form-control form-control-sm", min: 1, size: 100 %>
            </div>
            <div class="form-group">人</div>
          </div>
        </div>

        <div class="form-group d-flex">
          <%= f.submit '更新する', class: "btn btn-success text-light mr-3" %>
          <%= link_to '削除する', farmers_event_schedule_path(@event, @schedule), method: :delete, data: { confirm: "#{show_date(@schedule.date)}のイベントを削除しますか？" }, class: "btn btn-danger mr-3" %>
          <%= link_to "戻る", farmers_event_schedule_path(@event, @schedule), class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/farmers/schedules/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-5 offset-md-1 mb-4">
      <%= attachment_image_tag @event, :plan_image, class: "farm_pictures", fallback: asset_path('no_images/no_image_md.png'), size: '300x300' %>
    </div>
    <div class="col-12 col-md-5 mr-auto my-2">
      <h4 class="text-left mb-3"><%= @event.title %></h4>
      <h6><i class="fas fa-heart text-danger"></i> <%= @event.event_favorites.size %></h6>
      <% if current_farmer.id == @event.farmer_id %>
        <h6><i class="fas fa-bookmark text-success"></i> 予約数： <%= @schedule.reservations.size %></h6>
      <% end %>
      <%= safe_join(@event.body.split("\n"),tag(:br)) %>
    </div>
  </div>

  <%= render "farmers/schedules/show", event: @event, schedule: @schedule %>

  <div class="row">
    <div class="col-12 col-md-10 mx-auto mb-2 event">
      <%= render "farmers/events/access", event: @event %>
      <div class="form-group d-flex mt-3">
        <% if current_farmer.id == @event.farmer_id %>
          <% if @schedule.date > Date.current %>
            <%= link_to "日時以外の項目を編集する", edit_farmers_event_path(@event), class: "btn btn-success mr-3" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-12 col-md-10 mx-auto mb-2 event">
      <% if current_farmer.id == @event.farmer_id %>
        <div class="d-flex mb-4">
          <h5 class="mr-3">予約状況</h5>
        </div>
        <div class="col-7">
        <%= render "customers/reservations/index", reservations: @schedule.reservations, event: @event %>
        </div>
      <% end %>
      <%= link_to farmers_event_path(@event), class: "fixed-circle-btn" do %>イベント<br>概要へ<br>戻る<% end %>
    </div>
  </div>
</div>