config/routes.rb
Rails.application.routes.draw do

  # farmer
  devise_for :farmers, controllers: {
    sessions:      'farmers/sessions',
    registrations: 'farmers/registrations'
  }
  devise_scope :farmer do
    post 'farmers/guest_sign_in' => 'farmers/sessions#guest_sign_in'
  end

  namespace :farmers do
    resource :farmers, only: [:show, :edit, :update]
      get 'farmers/unsubscribe' => 'farmers#unsubscribe',  as: 'farmers_unsubscribe'
      patch 'farmers/withdraw'  => 'farmers#withdraw',     as: 'farmers_withdraw'
      get 'evaluations' => 'farmers#evaluations',  as: 'farmers_evaluations'
      get 'calender'    => 'farmers#calender',     as: 'farmers_calender'
    resources :recipes
    resources :events do
      resources :schedules, only: [:show, :edit, :update, :destroy]
      resources :chats, only: [:create]
    end
    resources :news, only: [:create, :destroy]
    resources :notices, only: [:index]
      delete 'notices/destroy_all' => 'notices#destroy_all'
  end

  # customer
  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    registrations: 'customers/registrations'
  }
  devise_scope :customer do
    post 'customers/guest_sign_in' => 'customers/sessions#guest_sign_in'
  end

  scope module: :customers do
    root 'homes#top'
    get 'about' => 'homes#about'
    get 'about_for_farmer' => 'homes#about_farmer'
    resources :events, only: [:index, :show] do
      resource :favorite_events, only: [:create, :destroy]
      resources :chats, only: [:create]
      resources :schedules, only: [:show] do
        get 'reservations/thanx'
        resources :reservations, only: [:new, :show, :create, :destroy]
        post 'reservations/confirm'
        post 'reservations/back'
      end
    end
    resources :farmers, only: [:index, :show] do
      resources :follows, only: [:create, :destroy]
      resources :evaluations, only: [:index, :create, :edit, :update, :destroy]
    end
    resources :notices, only: [:index]
      delete 'notices/destroy_all' => 'notices#destroy_all'
    resource :profiles, only: [:show, :edit, :update]
      get 'customer/followings' => 'profiles#followings', as: 'followings'
      get 'customer/favorites' => 'profiles#favorites', as: 'favorites'
      get 'customer/evaluations' => 'profiles#evaluations', as: 'evaluations'
      get 'customer/unsubscribe' => 'profiles#unsubscribe'
      patch 'customer/withdraw'  => 'profiles#withdraw'
    resources :recipes, only: [:index, :show] do
      resource :favorite_recipes, only: [:create, :destroy]
    end
    resources :reservations, only: [:index]
  end

  get 'search'=> 'searches#search', as: 'search'
  get 'sort'=> 'searches#sort', as: 'sort'

  # admin
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
  }

  namespace :admins do
    root 'farmers#index'
    resources :customers, only: [:index]
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable

  has_many :chats, dependent: :destroy
  has_many :evaluations, dependent: :destroy
  has_many :event_favorites, dependent: :destroy
  has_many :favorite_events, through: :event_favorites, source: :event
  has_many :follows, dependent: :destroy
  has_many :follow_farmers, through: :follows, source: :farmer
  has_many :recipe_favorites, dependent: :destroy
  has_many :favorite_recipes, through: :recipe_favorites, source: :recipe
  has_many :notices, dependent: :destroy
  has_many :reservations, dependent: :destroy

  validates :nickname, uniqueness: true, presence: true
  attachment :customer_image

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  def following?(farmer)
    follows.where(farmer_id: farmer.id).exists?
  end

  def reserved?(schedule)
    reservations.where(schedule_id: schedule.id).exists?
  end

  def self.guest_account
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.nickname = 'ゲスト'
      customer.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page]).reverse_order
  end
end

app/controllers/customers/chats_controller.rb
class Customers::ChatsController < ApplicationController
  before_action :authenticate_customer!
  skip_before_action :set_prefectures

  def create
    @chat = current_customer.chats.new(chat_params)
    @chat.event_id = params[:event_id]
    if @chat.save
      @chat.notice_created_by_customer(current_customer, params[:event_id])
    else
      render 'error'
    end
    @chats = Chat.where(event_id: params[:event_id])
  end

  private

  def chat_params
    params.require(:chat).permit(:chat)
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/evaluations_controller.rb
class Customers::EvaluationsController < ApplicationController
  before_action :authenticate_customer!, except: [:index]
  before_action :set_farmer, only: [:create, :edit]
  before_action :set_evaluation, only: [:edit, :update, :destroy]
  skip_before_action :set_prefectures

  def create
    @evaluation = current_customer.evaluations.new(evaluation_params)
    @evaluation.farmer_id = @farmer.id
    if @evaluation.save
      redirect_to farmer_path(@farmer), flash: { success: "レビューを投稿いたしました" }
    else
      redirect_to farmer_path(@farmer), flash: { danger: "星評価かコメントのいずれかを必ず入力してください。" }
    end
  end

  def index
    @evaluations = Evaluation.where(farmer_id: params[:farmer_id])
  end

  def edit
    unless current_customer.id == @evaluation.customer_id
      redirect_to profiles_path, flash: { danger: "他の方のレビューを編集することは出来ません" }
    end
  end

  def update
    if @evaluation.update(evaluation_params)
      redirect_to evaluations_path, flash: { success: "レビューを更新しました" }
    else
      render :edit
    end
  end

  def destroy
    @evaluation.destroy
    redirect_to evaluations_path, flash: { success: "レビューを削除しました" }
  end

  private

  def evaluation_params
    params.require(:evaluation).permit(:evaluation, :comment, :evaluation_image)
  end

  def set_farmer
    @farmer = Farmer.find(params[:farmer_id])
  end

  def set_evaluation
    @evaluation = Evaluation.find(params[:id])
  end
end

app/controllers/customers/events_controller.rb
class Customers::EventsController < ApplicationController
  def index
    @events = Event.where('end_date >= ?', Date.current).order(:start_date).page(params[:page])
  end

  def show
    @event = Event.find(params[:id])
    @schedules = @event.schedules.where(is_deleted: false, is_full: false)
    @schedule = @event.schedules.first
    @chat = Chat.new
    @chats = Chat.where(event_id: params[:id])
  end
end

app/controllers/customers/farmers_controller.rb
class Customers::FarmersController < ApplicationController
  def index
    @farmers = Farmer.where(is_deleted: false).page(params[:page]).reverse_order
  end

  def show
    @farmer = Farmer.find(params[:id])
    @events = Event.where(farmer_id: @farmer.id).where('end_date > ?', Date.current).order('created_at DESC').first(3)
    news_index = News.where(farmer_id: @farmer.id).order('created_at DESC')
    @news_last3 = news_index.first(3)
    @news_left = news_index.offset(3)
    @recipes = Recipe.where(farmer_id: @farmer.id).order('created_at DESC').first(3)

    @evaluation = Evaluation.new
    @evaluations = Evaluation.where(farmer_id: @farmer.id).order('created_at DESC').first(3)
    if @farmer.evaluations.blank?
      @average_rating = 0
    else
      @average_rating = @farmer.evaluations.average(:evaluation).round(2)
    end
  end
end

app/controllers/customers/favorite_events_controller.rb
class Customers::FavoriteEventsController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_event
  skip_before_action :set_prefectures

  def create
    favorite = @event.event_favorites.new(customer_id: current_customer.id)
    favorite.save
  end

  def destroy
    favorite = @event.event_favorites.find_by(customer_id: current_customer.id)
    favorite.destroy
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end
end

app/controllers/customers/favorite_recipes_controller.rb
class Customers::FavoriteRecipesController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_recipe
  skip_before_action :set_prefectures

  def create
    favorite = @recipe.recipe_favorites.new(customer_id: current_customer.id)
    favorite.save
  end

  def destroy
    favorite = @recipe.recipe_favorites.find_by(customer_id: current_customer.id)
    favorite.destroy
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:recipe_id])
  end
end

app/controllers/customers/follows_controller.rb
class Customers::FollowsController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_farmer
  skip_before_action :set_prefectures

  def create
    follow = @farmer.follows.new(customer_id: current_customer.id)
    follow.save
    @farmer.find_or_create_notice_of_follow(current_customer)
  end

  def destroy
    @farmer.follows.find_by(customer_id: current_customer.id).destroy
  end

  private

  def set_farmer
    @farmer = Farmer.find(params[:farmer_id])
  end
end

app/controllers/customers/homes_controller.rb
class Customers::HomesController < ApplicationController
  def top
    @farmers = Farmer.where(is_deleted: false).reverse_order.first(3)
    @recipes = Recipe.all.reverse_order.first(3)
    @events = Event.where("end_date >= ?", Date.current).reverse_order.first(3)
  end

  def about
  end
end

app/controllers/customers/notices_controller.rb
class Customers::NoticesController < ApplicationController
  skip_before_action :set_prefectures

  def index
    notices = current_customer.notices
    @notices = notices.where(action: ["チャット", "農業体験の内容更新", "農業体験のスケジュール更新", "お知らせ"]).order('created_at DESC').first(20)
    if notices.exists?
      unchecked_notices = notices.where(checked: false)
      unchecked_notices.update_all(checked: true)
    end
  end

  def destroy_all
    current_customer.notices.where(action: ["チャット", "農業体験の内容更新", "農業体験のスケジュール更新", "お知らせ"]).destroy_all
    redirect_to profiles_path, flash: { success: '通知をすべて削除しました' }
  end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/profiles_controller.rb
class Customers::ProfilesController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_customer
  skip_before_action :set_prefectures

  def show
  end

  def edit
    unless current_customer == @customer
      redirect_to profiles_path, flash: { danger: "他の方のプロフィールの変更は出来ません"}
    end
  end

  def update
    if @customer.update(customer_params)
      redirect_to profiles_path, flash: { success: "登録情報を更新しました" }
    else
      render :edit
    end
  end

  def unsubscribe
  end

  def withdraw
    @customer.update(is_deleted: true)
    redirect_to root_path, flash: { success: "ご利用いただき大変ありがとうございました！またのご利用を心よりお待ちしております。"}
  end

  def evaluations
    @evaluations = current_customer.evaluations
  end

  def favorites
    @favorite_recipes = current_customer.favorite_recipes
    @favorite_events = current_customer.favorite_events
  end

  def followings
    @followings = current_customer.follow_farmers.where(is_deleted: false).page(params[:page]).reverse_order
  end

  private

  def set_customer
    @customer = current_customer
  end

  def customer_params
    params.require(:customer).permit(:nickname, :customer_image)
  end
end

app/controllers/customers/recipes_controller.rb
class Customers::RecipesController < ApplicationController
  skip_before_action :set_prefectures

  def index
    @recipes = Recipe.page(params[:page]).reverse_order
  end

  def show
    @recipe = Recipe.find(params[:id])
    @tag_list = @recipe.tags.pluck(:tag)
  end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
        Customers::WelcomeMailer.complete_registration(resource).deliver_now
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
   def after_sign_up_path_for(resource)
    profiles_path
   end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #  super
  # end
end

app/controllers/customers/schedules_controller.rb
class Customers::SchedulesController < ApplicationController
  skip_before_action :set_prefectures

  def show
    @event = Event.find(params[:event_id])
    @schedule = @event.schedules.find(params[:id])
  end
end

app/views/customers/events/_index.html.erb
<div class="d-flex flex-row flex-wrap mt-4">
  <% if events.blank? %>
    <p>予約受付中の農業体験はありません</p>
  <% else %>
    <% events.each do |event| %>
      <div class="list-box mr-4 mb-3">
        <div class="image_top">
          <%= link_to event_path(event.id) do %>
            <%= attachment_image_tag event, :plan_image, :fill, 100, 70, class: "card-img-top" %>
          <% end %></div>
        <div class="title">
          <%= link_to event_path(event.id) do %>
            <h6 class="text-body"><%= event.title %></h6>
            <span class="text-body"><%= event.location.match(/^.{2,3}[都道府県]/).to_s %></span><br>
            <span class="text-body"><%= event.start_date.strftime('%m/%d') %>～<%= event.end_date.strftime('%m/%d') %></span>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/customers/events/_map.html.erb
<script>
  function initMap() {
    const location = { lat: <%= event.latitude %>, lng: <%= event.longitude %> };
    const map = new google.maps.Map(document.getElementById("map"), {
      zoom: 15,
      center: location,
    });
    const transitLayer = new google.maps.TransitLayer();
          transitLayer.setMap(map);
    const contentString = '集合場所：<%= event.location %>';
    const marker = new google.maps.Marker({
      position: location,
      map: map,
      title: contentString,
    });
    const infowindow = new google.maps.InfoWindow({
      content: contentString,
    });
    marker.addListener("click", () => {
      infowindow.open(map, marker);
    });
  }
</script>

<div id="map"></div>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap&libraries=&v=weekly" async defer></script>

app/views/customers/events/_top.html.erb
<h4 class="text-left mb-3"><%= event.title %></h4>
<h6 class="text-left mb-3">企画：<%= link_to event.farmer.name, farmer_path(event.farmer) %></h6>
<% if customer_signed_in? %>
  <h6 class="favorite-btn"><%= render 'customers/favorite_events/favorite-btn', event: event %></h6>
<% else %>
  <h6><i class="fas fa-heart text-danger"></i> <%= event.event_favorites.size %></h6>
<% end %>
<%= safe_join(event.body.split("\n"),tag(:br)) %>

app/views/customers/events/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-11 col-md-10 mx-auto">
      <h4 class="mb-4">予約受付中の農業体験一覧</h4>
    </div>
    <div class="col-10 mx-auto col-md-3 offset-md-1 side-bar">
      <h6 class="text-center">エリアから探す</h6>
      <%= render 'searches/event_area', regions: @regions %>
    </div>
    <div class="col-md-8 main-content d-none d-md-block">
      <div class="form-row text-left mb-3">
        <%= render 'searches/event_search' %>
        <%= render 'searches/eventdate_search' %>
        <%= render 'searches/event_sort' %>
      </div>
      <div id="index_all">
        <%= render 'customers/events/index', events: @events %>
        <%= paginate @events %>
      </div>
      <div id="index_sort">
        <%= render 'customers/events/index', events: @records %>
      </div>
    </div>
  </div>
</div>

app/views/customers/events/show.html.erb
<div class="container">
  <div class="row">
    <% if customer_signed_in? %>
      <a class="fixed-chat-btn" href="#chat">チャット</a>
    <% end %>
    <div class="col-12 col-md-5 offset-md-1 mb-4">
      <%= attachment_image_tag @event, :plan_image, class: "farm_pictures", fallback: asset_path('no_images/no_image_md.png'), size: '300x300' %>
    </div>
    <div class="col-12 col-md-5 mr-auto my-2" id="event_<%= @event.id %>">
      <%= render 'customers/events/top', event: @event %>
    </div>
  </div>

  <div class="row">
    <div class="col-12 col-md-10 mx-auto mb-2 event">
      <h5 class="mb-2">イベント概要</h5>
      <table class="table">
        <tbody>
          <tr>
            <th>イベント期間</th>
            <td>
              <p>ご予約の際は、以下より希望の日程をお選びください。</p>
              <% @schedules.each do |schedule| %>
                <%= link_to event_schedule_path(event_id: @event.id, id: schedule.id), class: "btn btn-success btn-sm mr-3" do %>
                  <%= show_date(schedule.date) %>
                <% end %>
              <% end %>
              </td>
          </tr>
          <tr>
            <th>開催時刻</th>
            <td><%= show_time(@schedule.start_time) %> ～ <%= show_time(@schedule.end_time) %><br>
                <span class="required">日程により個別に変更されている可能性がございますので、詳細は上記リンク先よりご確認ください。</span></td>
          </tr>
          <tr>
            <th>イベント参加費（税込）/人</th>
            <td><%= converting_to_jpy(@event.fee) %></td>
          </tr>
          <tr>
            <th>キャンセルポリシー</th>
            <td><%= @event.cancel_change %></td>
          </tr>
          <tr>
            <th>そのほか</th>
            <td><%= @event.etc %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-12 col-md-10 mx-auto mb-2 event">
      <%= render "farmers/events/access", event: @event %>
    </div>
  </div>

  <div class="row">
    <div class="col-12 col-md-8 mx-auto mb-2 mt-4">
      <h5 class="mb-2 text-center" id="chat">ご相談、ご連絡フォーム</h5>
      <div id="error"></div>
      <% if customer_signed_in? %>
        <%= form_with model: [@event, @chat], url: event_chats_path(@event, @chat) do |f| %>
          <%= f.text_area :chat, class: "form-control form-control-sm", placeholder: "Chat" %>
          <%= f.submit "送信", class: "btn btn-success btn-sm mt-2" %>
        <% end %>
      <% end %>
    </div>
    <div class="col-12 col-md-8 mx-auto mb-2 mt-3">
      <div class="chat_index">
        <%= render "farmers/chats/index", chats: @chats %>
      </div>
    </div>
  </div>
</div>