config/routes.rb
Rails.application.routes.draw do

  # farmer
  devise_for :farmers, controllers: {
    sessions:      'farmers/sessions',
    registrations: 'farmers/registrations'
  }
  devise_scope :farmer do
    post 'farmers/guest_sign_in' => 'farmers/sessions#guest_sign_in'
  end

  namespace :farmers do
    resource :farmers, only: [:show, :edit, :update]
      get 'farmers/unsubscribe' => 'farmers#unsubscribe',  as: 'farmers_unsubscribe'
      patch 'farmers/withdraw'  => 'farmers#withdraw',     as: 'farmers_withdraw'
      get 'evaluations' => 'farmers#evaluations',  as: 'farmers_evaluations'
      get 'calender'    => 'farmers#calender',     as: 'farmers_calender'
    resources :recipes
    resources :events do
      resources :schedules, only: [:show, :edit, :update, :destroy]
      resources :chats, only: [:create]
    end
    resources :news, only: [:create, :destroy]
    resources :notices, only: [:index]
      delete 'notices/destroy_all' => 'notices#destroy_all'
  end

  # customer
  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    registrations: 'customers/registrations'
  }
  devise_scope :customer do
    post 'customers/guest_sign_in' => 'customers/sessions#guest_sign_in'
  end

  scope module: :customers do
    root 'homes#top'
    get 'about' => 'homes#about'
    get 'about_for_farmer' => 'homes#about_farmer'
    resources :events, only: [:index, :show] do
      resource :favorite_events, only: [:create, :destroy]
      resources :chats, only: [:create]
      resources :schedules, only: [:show] do
        get 'reservations/thanx'
        resources :reservations, only: [:new, :show, :create, :destroy]
        post 'reservations/confirm'
        post 'reservations/back'
      end
    end
    resources :farmers, only: [:index, :show] do
      resources :follows, only: [:create, :destroy]
      resources :evaluations, only: [:index, :create, :edit, :update, :destroy]
    end
    resources :notices, only: [:index]
      delete 'notices/destroy_all' => 'notices#destroy_all'
    resource :profiles, only: [:show, :edit, :update]
      get 'customer/followings' => 'profiles#followings', as: 'followings'
      get 'customer/favorites' => 'profiles#favorites', as: 'favorites'
      get 'customer/evaluations' => 'profiles#evaluations', as: 'evaluations'
      get 'customer/unsubscribe' => 'profiles#unsubscribe'
      patch 'customer/withdraw'  => 'profiles#withdraw'
    resources :recipes, only: [:index, :show] do
      resource :favorite_recipes, only: [:create, :destroy]
    end
    resources :reservations, only: [:index]
  end

  get 'search'=> 'searches#search', as: 'search'
  get 'sort'=> 'searches#sort', as: 'sort'

  # admin
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
  }

  namespace :admins do
    root 'farmers#index'
    resources :customers, only: [:index]
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  skip_before_action :set_prefectures

	def search
		@model = params[:model]
		case @model
		when 'recipe' then
			@content = params[:content]
			tags = Tag.tag_like(@content)
			if tags.present?
				@records = Recipe.search_for(@content, tags)
			else
				@records = Recipe.title_like(@content)
			end
			@records = @records.where(farmer_id: current_farmer.id) if farmer_signed_in?
		when 'event' then
			if params.has_key?(:prefecture)
				@content = params[:prefecture]
				@records = Event.search_for(@content, 'forward').where('end_date >= ?', Date.current)
			elsif params.has_key?(:event_date)
				@content = params[:event_date]
				if farmer_signed_in?
					@records = current_farmer.events.search_for(@content, 'date')
				else
					@records = Event.search_for(@content, 'date').where('end_date >= ?', Date.current)
				end
			else
				@content = params[:content]
				if farmer_signed_in?
					@records = current_farmer.events.search_for(@content, 'partial')
				else
					@records = Event.search_for(@content, 'partial').where('end_date >= ?', Date.current)
				end
			end
		else
			if params.has_key?(:prefecture)
				@content = params[:prefecture]
				@records = Farmer.search_for(@content, 'forward')
			else
				@content = params[:content]
				@records = Farmer.search_for(@content, 'partial')
			end
		end
	end

	def sort
		@model = params[:model]
		@method = params[:keyword]
		case @model
		when 'recipe'
			@records = Recipe.sorts(@method)
			@records = @records.where(farmer_id: current_farmer.id) if farmer_signed_in?
		when 'event'
			if farmer_signed_in?
				@records = current_farmer.events.sorts(@method)
			else
				@records = Event.sorts(@method).where('end_date >= ?', Date.current)
			end
		else
			@records = Farmer.sorts(@method)
		end
	end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_event_area.html.erb
<div class="search-area-group mt-3">
  <% regions.each do |region_name, prefectures| %>
  <div class="form-group">
    <h6>
      <%= region_name %>
    </h6>
    <% prefectures.each do |prefecture| %>
     <%= link_to prefecture, search_path(prefecture: prefecture, model: 'event') %>
    <% end %>
    </div>
  <% end %>
</div>

app/views/searches/_event_search.html.erb
<div class="search-form form-inline mr-3">
  <%= form_with url: search_path, method: :get, local: true do |f| %>
    <%= f.text_field :content, placeholder: "Search", autofocus: true, class: "form-control form-control-sm" %>
    <%= f.hidden_field :model, :value => 'event' %>
    <%= f.button :type => "submit", style: 'border-style: none;', class: "btn btn-sm btn-warning" do %>
      <i class="fas fa-search"></i>
    <% end %>
  <% end %>
</div>

app/views/searches/_event_sort.html.erb
<div class="search-form form-inline" id="sort">
  <%= form_with url: sort_path, method: :get do |f| %>
    <%= f.select :keyword, [["イベント日（昇順）", "asc"], ["イベント日（降順）", "desc"],
                            ["人気順", "like"], ["投稿が新しい順", "new"]], {}, class: "custom-select custom-select-sm" %>
    <%= f.hidden_field :model, :value => 'event' %>
    <%= f.button :type => "submit", style: 'border-style: none;', class: "btn btn-sm btn-primary" do %>
      <i class="fas fa-sort"></i>
    <% end %>
  <% end %>
</div>

app/views/searches/_eventdate_search.html.erb
<div class="search-form form-inline mr-3">
  <%= form_with url: search_path, method: :get, local: true do |f| %>
    <%= f.date_field :event_date, placeholder: "Search", class: "form-control form-control-sm" %>
    <%= f.hidden_field :model, :value => 'event' %>
    <%= f.button :type => "submit", style: 'border-style: none;', class: "btn btn-sm btn-warning" do %>
      <i class="fas fa-search"></i>
    <% end %>
  <% end %>
</div>

app/views/searches/_farmer_area.html.erb
<div class="search-area-group mt-3">
  <% regions.each do |region_name, prefectures| %>
  <div class="form-group">
    <h6>
      <%= region_name %>
    </h6>
    <% prefectures.each do |prefecture| %>
     <%= link_to prefecture, search_path(prefecture: prefecture, model: 'farmer') %>
    <% end %>
    </div>
  <% end %>
</div>

app/views/searches/_farmer_search.html.erb
<div class="search-form form-inline mr-3">
  <%= form_with url: search_path, method: :get, local: true do |f| %>
    <%= f.text_field :content, placeholder: "Search", autofocus: true, class: "form-control form-control-sm" %>
    <%= f.hidden_field :model, :value => 'farmer' %>
    <%= f.button :type => "submit", style: 'border-style: none;', class: "btn btn-sm btn-warning" do %>
      <i class="fas fa-search"></i>
    <% end %>
  <% end %>
</div>

app/views/searches/_farmer_sort.html.erb
<div class="search-form form-inline" id="sort">
  <%= form_with url: sort_path, method: :get do |f| %>
    <%= f.select :keyword, [ ["登録が新しい順", "new"], ["登録が古い順", "old"], ["フォロワー数", "follows"], ["評価順", "high"]], {}, class: "custom-select custom-select-sm" %>
    <%= f.hidden_field :model, :value => 'farmer' %>
    <%= f.button :type => "submit", style: 'border-style: none;', class: "btn btn-sm btn-primary" do %>
      <i class="fas fa-sort"></i>
    <% end %>
  <% end %>
</div>

app/views/searches/_recipe_search.html.erb
<div class="search-form form-inline mr-3">
  <%= form_with url: search_path, method: :get, local: true do |f| %>
    <%= f.text_field :content, placeholder: "Search", autofocus: true, class: "form-control form-control-sm" %>
    <%= f.hidden_field :model, :value => 'recipe' %>
    <%= f.button :type => "submit", style: 'border-style: none;', class: "btn btn-sm btn-warning" do %>
      <i class="fas fa-search"></i>
    <% end %>
  <% end %>
</div>

app/views/searches/_recipe_sort.html.erb
<div class="search-form form-inline" id="sort">
  <%= form_with url: sort_path, method: :get do |f| %>
    <%= f.select :keyword, [["投稿が新しい順", "new"], ["人気順", "likes"]], {}, class: "custom-select custom-select-sm" %>
    <%= f.hidden_field :model, :value => 'recipe' %>
    <%= f.button :type => "submit", style: 'border-style: none;', class: "btn btn-sm btn-primary" do %>
      <i class="fas fa-sort"></i>
    <% end %>
  <% end %>
</div>

app/views/searches/search.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-10 mx-auto">
      <h4 class="mb-4">「<%= @content %>」の検索結果</h4>
        <% if farmer_signed_in? %>
          <% if @model == 'recipe' %>
            <%= render 'farmers/recipes/index', recipes: @records %>
          <% elsif @model == 'Tag' %>
            <%= render 'farmers/recipes/index', recipes: @records %>
          <% elsif @model == 'event' %>
            <%= render 'farmers/events/index', events: @records %>
          <% else %>
            <%= render 'customers/farmers/index', farmers: @records %>
          <% end %>
        <% else %>
          <% if @model == 'recipe' %>
            <%= render 'customers/recipes/index', recipes: @records %>
          <% elsif @model == 'Tag' %>
            <%= render 'customers/recipes/index', recipes: @records %>
          <% elsif @model == 'event' %>
            <%= render 'customers/events/index', events: @records %>
          <% else %>
            <%= render 'customers/farmers/index', farmers: @records %>
          <% end %>
        <% end %>
    </div>
  </div>
</div>

app/views/searches/sort.js.erb
$('#index_all').hide();

<% if @farmer.blank? %>
  <% if @model == "recipe" %>
    $('#index_sort').html('<%= j(render 'customers/recipes/index', recipes: @records) %>');
  <% elsif @model == "event" %>
    $('#index_sort').html('<%= j(render 'customers/events/index', events: @records) %>');
  <% else %>
    $('#index_sort').html('<%= j(render 'admins/farmers/index', farmers: @records) %><%= j(render 'admins/farmers/raty-js') %>');
  <% end %>
<% else %>
  <% if @model == "recipe" %>
    $('#index_sort').html('<%= j(render 'farmers/recipes/index', recipes: @records) %>');
  <% else %>
    $('#index_sort').html('<%= j(render 'farmers/events/index', events: @records) %>');
  <% end %>
<% end %>

$('#index_sort').show();